pipewire & pipewire-pulse & pipewire-media-session &
xrdb -merge ~/.config/Xresources
xinput set-prop pointer:"COMPANY  USB Device " "libinput Natural Scrolling Enabled" 1
xwallpaper --zoom ~/pictures/nord.jpg
xcompmgr &
exec dwm
#exec startxfce4
